sudo: required
services:
  - docker

before_install:
  - docker build -t stephenjdawson/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephenjdawson/docker-react npm run test



